### ISSUE TITLE
html body should be added to message *after* text

### ISSUE THREAD

**Issue by samm81** [parkerduckworth/bamboo_gmail#5]
According to [this article](https://alexpounds.com/blog/2014/09/30/why-your-multipart-emails-show-up-as-plaintext) the client, if the user does not specify a preference, will render the *last* part of a multipart email.

So `|> put_html_body(email)` (https://github.com/parkerduckworth/bamboo_gmail/blob/master/lib/bamboo/adapters/gmail_adapter.ex#L96) should be swapped with `|> put_text_body(email)` (https://github.com/parkerduckworth/bamboo_gmail/blob/master/lib/bamboo/adapters/gmail_adapter.ex#L97).

**Comment by lovebes** [comment]
oh my gosh I just wasted two hours on this. Thank you!! @samm81 do you suggest `put_html_body()` to be AFTER `put_text_body`?

**Comment by parkerduckworth** [comment]
@samm81 thanks for the suggestion.

@lovebes sorry! thanks for making the fix.
